apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - name: wpport
      protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wp_img
        imagePullPolicy: Never
        # env:
        # - name: WORDPRESS_DB_HOST
        #   value: mysql-deploy
        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        ports:
        - containerPort: 5050
          name: wpport
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
