apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deploy
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf_img
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersocket
      volumes:
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock