apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv
      protocol: TCP
      port: 10015
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        # env:
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        ports:
        - containerPort: 21
          name: ftp
        - containerPort: 10015
          name: pasv
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /home
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pvc