apiVersion: v1
kind: Service
metadata:
  name: pma-svc
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - name: pmaport
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: pma_img
        imagePullPolicy: Never
        # env:
        # - name: WORDPRESS_DB_HOST
        #   value: mysql-deploy
        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        ports:
        - containerPort: 5000
          name: pmaport
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
